name: Publish to npm

on:
  push:
    branches:
      - master

jobs:
  npm-publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install, build, and test
      run: |
        npm ci
        npm test
      env:
        CI: true
    
    - name: audit tools
      run: npm audit --audit-level=moderate
    
    - name: npm publish
      run: npm publish
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }} # how to do this?
